### ISSUE TITLE
Double-tap to select Quicksilver can cause crash

### ISSUE THREAD

**Issue by SuperfieldCU** [serpentiem/ddmk#102]
Using 2.6 Beta 2. Immediately after completing the Timesteed boss, I decided to try out the double-tap feature for selecting Quicksilver. I was in Trickster and pressed up on the D-Pad and the game crashed. I started the game back up, turned off double-tap, beat the mission and got Quicksilver again, and then saved. I turned double-tap back on and went to Mission 3, and everything worked fine, Quicksilver and all. But when I tried to switch to Quicksilver against Cerberus, it crashed again.

I had Style Switcher and Weapon Switcher on, Infinite Rainstorm, Air Hike Core, and Invert Camera X all enabled. Force Single Actor was not on. I've also got the widescreen menus mod, an HD UI mod, and an improved .wmv cutscenes mod activated with the Prefer Local Files option.

**Comment by Dosudude** [comment]
Having this problem with crashes since I picked up Quicksilver. Specifically Mission 14 for me. Any style switching from then on and my game crashes.

I have no extraordinarily taxing settings on (to my knowledge). I use the style + weapon switcher, universal air hike, limiting my ranged weapons to Pistols and Spiral, and the orb catcher. I also put on reduced Devil guage usage to get to the enemies faster to show what I'm talking about. It crashes as soon as I weapon swap in the room with the enemies.

[https://youtu.be/dKoE7eoCEpo](url)

**Comment by serpentiem** [comment]
Try again with the latest nightly. If the problem persists, open a new issue and attach your log files.
