### ISSUE TITLE
4SE won't launch with DDMK installed.

### ISSUE THREAD

**Issue by TheTwelfthDoctor** [serpentiem/ddmk#105]
Hi!

I recently installed DDMK and following the installation guide on the wiki. I can play the game fine but the moment I install DDMK the game refuses to go past a black screen and just closes on it's own. Not entirely sure why this is happening. Perhaps I messed up the installation or it's something wrong with my system. I'm on Windows 10 Pro 64-bit. My game version is the latest version on Steam and I'm logged in while launching the game, I've tried the .exe without using the downgrade and with and it still wouldn't launch.

I've tried launching the game as administrator and that didn't help either. This is on DDMK 2.5

I've attached my log files.

[Kyrie.txt](https://github.com/serpentiem/ddmk/files/4243973/Kyrie.txt)
[dinput8.txt](https://github.com/serpentiem/ddmk/files/4243975/dinput8.txt)

**Comment by rabbitA9868** [comment]
**I just dont know why,it still not working yet**

**Comment by DragonOverlord2012** [comment]
Yeah this confuzzled me for a bit but as it turns out it was a "directions unclear; got dick stuck in toaster" situation.  When pulling the xdelta3 files I pulled both .exe's because the instructions said "pull the files from these downloads" without any further citation as to which of the two .exe files to use.  Not knowing, stupid me assumed both.  Undid the downgrade by restoring the original DMC4SE executable file and steam_api.dll, and ran the downgrade process again this time only using the xdelta3 file marked "xdelta3-3.0.11-x86_64.exe" and the "xdelta3-3.0.11.tar.gz", and it works fine now.

**Comment by serpentiem** [comment]
Try again with the [latest nightly](https://github.com/serpentiem/ddmk/releases/tag/2.7nightly22). If the problem persists, open a new issue.
