### ISSUE TITLE
Normal progession

### ISSUE THREAD

**Issue by bill5499** [serpentiem/ddmk#217]
Is it possible to have style and weapon switching without it all fully upgraded from the start? I don't like messing with the progression unlock system.

**Comment by SteveCraft1** [comment]
I'm not sure but It seems that it's not possible to have newgame stuff with 2.7 version,you can try 2.6 since It don't force max upgraded styles or weapons but It can crash time from time and also mission 19 is Impossible to pass on 2.6

**Comment by bill5499** [comment]
Yeah, I might just do that. Although I noticed it said to solve the whole crash issue with Arkham is to disabled the mod temporarily. Does that mean I have to delete the files? Or just unchecked everything in the menu?

**Comment by bill5499** [comment]
> 
> 
> I'm not sure but It seems that it's not possible to have newgame stuff with 2.7 version,you can try 2.6 since It don't force max upgraded styles or weapons but It can crash time from time and also mission 19 is Impossible to pass on 2.6

Yeah, I might just do that. Although I noticed it said to solve the whole crash issue with Arkham is to disabled the mod temporarily. Does that mean I have to delete the files? Or just unchecked everything in the menu?

**Comment by SteveCraft1** [comment]
> > I'm not sure but It seems that it's not possible to have newgame stuff with 2.7 version,you can try 2.6 since It don't force max upgraded styles or weapons but It can crash time from time and also mission 19 is Impossible to pass on 2.6
> 
> Yeah, I might just do that. Although I noticed it said to solve the whole crash issue with Arkham is to disabled the mod temporarily. Does that mean I have to delete the files? Or just unchecked everything in the menu?

just change Dinput8.dll to some other name to disable the mod entirely,then enable after that battle

**Comment by bill5499** [comment]
> 
> 
> > > I'm not sure but It seems that it's not possible to have newgame stuff with 2.7 version,you can try 2.6 since It don't force max upgraded styles or weapons but It can crash time from time and also mission 19 is Impossible to pass on 2.6
> > 
> > 
> > Yeah, I might just do that. Although I noticed it said to solve the whole crash issue with Arkham is to disabled the mod temporarily. Does that mean I have to delete the files? Or just unchecked everything in the menu?
> 
> just change Dinput8.dll to some other name to disable the mod entirely,then enable after that battle,you can even change it to Dinput.dll that it will disable it

Aight cool. BTW does this mod change anything for DMC 1 and 2?

**Comment by SteveCraft1** [comment]
i'm not sure if you noticed but DDMK 2.7 version only have Mary.dll and Dinput8.dll,Dinput8 is to activate DDMK while Mary.dll is to use DDMK on DMC3,there is Eva.dll which activate DDMK for DMC1 and Lucia.dll which activate for DDMK for DMC2,the last version that you can have DDMK on DMC2 and 1 is 2.6 hotfix,after this version you won't see DDMK for DMC1 and DMC2
to say easier,it won't but i don't recommend using DDMK on DMC1 while playing normally because it broke spawn points(when you begin a mission) by mission 2 to the end making it impossible to play,also DMC2 only have a frame limiter

**Comment by bill5499** [comment]
> 
> 
> i'm not sure if you noticed but DDMK 2.7 version only have Mary.dll and Dinput8.dll,Dinput8 is to activate DDMK while Mary.dll is to use DDMK on DMC3,there is Eva.dll which activate DDMK for DMC1 and Lucia.dll which activate for DDMK for DMC2,the last version that you can have DDMK on DMC2 and 1 is 2.6 hotfix,after this version you won't see DDMK for DMC1 and DMC2
> to say easier,it won't but i don't recommend using DDMK on DMC1 while playing normally because it broke spawn points(when you begin a mission) by mission 2 to the end making it impossible to play,also DMC2 only have a frame limiter

So do I have to disable the mod completely like above or just not touch anything in the menu?

**Comment by SteveCraft1** [comment]
if you use 2.6 Hotfix(which is the better version of before 2.7),you gonna need to disable the mod by either changing dinput8.dll name or dragging it out of dmchdc folder because it will crash on mission 19 boss battle,if you use a version before that,you'll only need to not activate anything on it to be able to play the second phase boss fight

**Comment by bill5499** [comment]
> 
> 
> if you use 2.6 Hotfix(which is the better version of before 2.7),you gonna need to disable the mod by either changing dinput8.dll name or dragging it out of dmchdc folder because it will crash on mission 19 boss battle even if you don't touch anything on menu,if you use a version before that,you'll only need to not activate anything on it to be able to play the second phase boss fight

Yeah I got that part, I was talking about how to disable it completely for DMC 1 and 2 since I don't actually need it for those games

**Comment by SteveCraft1** [comment]
To disable It completely Just don't put Eva.dll and Lucia.dll on the folder

**Comment by bill5499** [comment]
> 
> 
> To disable It completely Just don't put Eva.dll and Lucia.dll on the folder

Okay thanks

**Comment by SteveCraft1** [comment]
You're welcome

**Comment by Proutbedaine** [comment]
> Is it possible to have style and weapon switching without it all fully upgraded from the start? I don't like messing with the progression unlock system.

Yes I made posts/threads regarding that too (Just go a few threads down, I really go in detail about it). I'd love for it to be optional too. I did use DDMK 2.6 for DMC3 and I must admit it almost does everything I need it to. 

I think the only things that bothers me with that version are:

- that the UI of the mod menus aren't adapted to my screen well. I use a 55" 4k TV and the UI size is good BUT to interact with it in any way I have to guess where my "actual" cursor is because where I point with my cursor does not point at the same place within the UI :T. But it is manageable though, just annoying and a bit more time consuming to navigate xD.

- That the devil form doesn't update according to the weapon and you have to choose one that's always going to show up during the mission.

- Sadly in that version it doesn't seem to have the arbitrary selection with the radial menu, but it's a sacrifice I don't mind making for now.

- Also Mission 19, as I have been informed, still crashes the game at it's second part of the fight so you have to deactivate the mod to go through it. Which is also a sacrifice that doesn't bother me too much.

**Comment by berserkingyadis** [comment]
+1 for making the unlocked progression optional/non-default in 2.7. i have seen alot of people mentioning this on here, reddit and the steam forums, there is high demand for not unlocking everything instantly, myself included.

**Comment by serpentiem** [comment]
> Is it possible to have style and weapon switching without it all fully upgraded from the start? I don't like messing with the progression unlock system.

No, it's necessary to set the expertise to max, otherwise characters will unexpectedly lose access to moves.
