### ISSUE TITLE
Boss Lady crashes the game when attacking an enemy.

### ISSUE THREAD

**Issue by youwereeatenbyalid** [serpentiem/ddmk#220]
[dinput8.txt](https://github.com/serpentiem/ddmk/files/6796362/dinput8.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/6796363/Mary.txt)
Pretty straightforward. Mission 4, Lady as main character, boss lady as secondary character. Entering a combat scenario and performing X+Back move with boss lady on an enemy crashes the game.

**Comment by SteveCraft1** [comment]
i checked and the problem is Lady itself,if she uses lock on she will go on T pose and crash the game,changing to Boss Lady don't solve the issue,Lady still gonna T pose while not appearing and causing the crash,try to have Dante or Vergil as main character and Boss Lady as secondary character to check if it still crash

**Comment by serpentiem** [comment]
That's not on me. The game's playable Lady is unfinished and not accessible by default. I suggest you use Dante instead and set Force Files to Lady to get a better experience.
