### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by blazecharzard** [serpentiem/ddmk#228]
After installing DDMK 2.7 Mary Nightly 30 June 2021 last night I have become unable to save any of the games in the Devil May Cry HD Collection. This problem still persists after multiple uninstalling and reinstalls. Please help with fixing this problem.

![20210820215142_1](https://user-images.githubusercontent.com/89284924/130306942-4e8f75b4-a211-4ad6-a77d-4660b32dc887.jpg)
![20210820215242_1](https://user-images.githubusercontent.com/89284924/130306951-965eb501-30e9-4653-9eba-899ef86a108c.jpg)
![20210820192209_1](https://user-images.githubusercontent.com/89284924/130306960-72dae071-9ac1-4af4-b841-e8d7f7ba6eea.jpg)

**Comment by serpentiem** [comment]
Are you unable to load as well?

**Comment by Ringotaker** [comment]
Hi, I know i wasn't the first one with the issue... So here's how it's going so far for me. Loading works just fine, the problem is saving. Yesterday I installed version 2.7 Nightly and I was able to save at first, however today i'm unable to do so, don't know the reason. Tried re-installing and re-applying patch, but it doesn't make a difference

**Comment by serpentiem** [comment]
Try again with the [latest release](https://github.com/serpentiem/ddmk/releases/tag/2.7Release).

Maybe your anti malware solution is overly cautious. Try adding exceptions for relevant `.exe` and `.dll` files.
