### ISSUE TITLE
Is it possible to leave the Switch version identical?

### ISSUE THREAD

**Issue by NaulDrade** [serpentiem/ddmk#276]
Hello sorry for the inconvenience, but I wanted to know if it is possible through the mod to transform the DMC3SE in the version of Nintendo Switch, leaving only the change of style and picking up the items as you progress in the game? (I am using a translator, sorry if it is difficult to understand the text)

**Comment by K-MH21** [comment]
Yes you can, but not 100%.

Follow these steps to have the closest experience with the switch version

1. Enable the actor module
2. For the character count, pick 1
3. Right under the main label, select the character you want to play with
4. Right the costume label, tick the ignore button

![image](https://user-images.githubusercontent.com/68538334/170702925-9aab756e-d612-428e-974c-5a95c41144f7.png)

5. In the style option, instead of Quicksilver, choose Swordmaster, and instead of Doppelganger, choose Gunslinger
6. For both melee weapons and ranged weapons, pick 1
![image](https://user-images.githubusercontent.com/68538334/170706295-8b57b333-877e-44ab-a5b7-50cec9307f06.png)

Keep in mind that
- As you progress in the game and unlock more weapons and styles, you have to choose them in the mod menu as well.
- In some parts of the game, the actor module will be disabled, which disables what we have done above
