### ISSUE TITLE
Pirated Version

### ISSUE THREAD

**Issue by Filp0** [serpentiem/ddmk#308]
Is there anyway to make this mod work on pirated version pls?

**Comment by nosh62** [comment]
As long as there's a "DMC HDC" folder on your PC, you should be able to do what's in the instructions. Also, be sure you haven't pirated the DMC3 SE version of the game; since DDMK doesn't work with that one. It only works with the DMC HDC bundle. I don't know much about how the pirated files are since I've never pirated the game.

**Comment by K-MH21** [comment]
No support for pirated copies.
