### ISSUE TITLE
DMC3: How do you get rid of this gross console based customization menu?

### ISSUE THREAD

**Issue by ComeOnAndSam** [serpentiem/ddmk#309]
This: https://i.imgur.com/ZbldaiZ.png

Where's the in game menu and how do I get it back? In my opinion, this makes the mod unusable. This screen is so hard to read and gives no info about the abilities Im trying to unlock.

It also, to my recollection, didn't used to be like this, at least in the SD version of the mod.

**Comment by nosh62** [comment]
TL;DR: You can't, and it's to avoid crashing the game unnecessarily.

The only way to get the default menu again is by disabling the Actor Module> For that, you'll need to turn it off on the menu, then exit and re-enter the room with the Divinity Statue (alternatively, you can disable the Actor Module before entering the room).
The only places where this won't be a problem since the Divinity Statues will appear by themselves are the following parts of the game:
https://user-images.githubusercontent.com/73554591/161397723-0b265ebe-8ff7-43b1-b15e-ad74e7d7c321.jpg
