### ISSUE TITLE
DDMK 2.6b - DMC3 Mission 19 Second Phase fight with Arkham CRASH

### ISSUE THREAD

**Issue by fronczek7f** [serpentiem/ddmk#89]
When I start second phase, after Vergil join to fight get insta crash. It happened only once because it was late and I didn't feel like going through this mission again :P. I will check again today if this error occurs always or only randomly.

Here game logs:
[dinput8.txt](https://github.com/serpentiem/ddmk/files/4015336/dinput8.txt)
[Eva.txt](https://github.com/serpentiem/ddmk/files/4015337/Eva.txt)
[Mary.txt](https://github.com/serpentiem/ddmk/files/4015338/Mary.txt)

**Comment by fronczek7f** [comment]
Yup. This problem make crash every time when i starting second phase with Vergil.

**Comment by FanSeaJay** [comment]
If you read the notes it mentions this and says the only work around right now is to disable the mod. My issue is I don't know how to disable the mod. I disabled everything except for infinite DT because I wanted to rush back into the place where it crashes at, but forgot to disable that when Vergil joins. Going to try it again and turn off dt when it gets to that point.

**Comment by serpentiem** [comment]
It's a known bug. I'm working on it.

**Comment by serpentiem** [comment]
Should be fixed by now.
